// This file is auto-generated by @hey-api/openapi-ts

export type HealthCheckResponse = {
    name?: string;
    version?: string;
};

export type GetAuctionData = {
    /**
     * The ID of the auction.
     */
    id: number;
    /**
     * Tenant ID
     */
    tenant: string;
};

export type GetAuctionResponse = {
    data?: {
        id?: number;
        sku?: string;
        title?: string;
        listing_type?: string;
        listing_type_tier?: string;
        listing_type_weight?: number;
        cur_bid?: string;
        reserve_met?: boolean;
        high_bidder_id?: string;
        num_bids?: number;
        price?: number;
        type?: string;
        make_an_offer?: boolean;
        no_reserve?: boolean;
        width?: number;
        length?: number;
        depth?: number;
        weight?: number;
        ends_at?: string;
        created_at?: number;
        has_video?: boolean;
        seller?: string;
        seller_country?: string;
        on_sale?: boolean;
        coupon_type?: string;
        coupon_value?: string;
        categories?: {
            lvl0?: string;
        };
        variants?: Array<{
            '2'?: string;
        }>;
        colours?: Array<(string)>;
        image?: string;
        url?: string;
        url_store?: string;
        description?: string;
    };
};

export type CreateAguestUserData = {
    requestBody: {
        /**
         * Must not be greater than 50 characters.
         */
        firstname: string;
        /**
         * Must not be greater than 50 characters.
         */
        surname: string;
        /**
         * Must be a valid email address. Must not be greater than 50 characters.
         */
        email: string;
        /**
         * Must not be greater than 20 characters.
         */
        phone: string;
        /**
         * Must not be greater than 255 characters.
         */
        address: string;
        /**
         * Must not be greater than 50 characters.
         */
        city: string;
        /**
         * Must not be greater than 50 characters.
         */
        state: string;
        country: string;
        /**
         * Must not be greater than 30 characters.
         */
        postcode: string;
    };
};

export type $OpenApiTs = {
    '/v3': {
        get: {
            res: {
                200: {
                    name?: string;
                    version?: string;
                };
            };
        };
    };
    '/v3/{tenant}/auctions/{id}': {
        get: {
            req: GetAuctionData;
            res: {
                200: {
                    data?: {
                        id?: number;
                        sku?: string;
                        title?: string;
                        listing_type?: string;
                        listing_type_tier?: string;
                        listing_type_weight?: number;
                        cur_bid?: string;
                        reserve_met?: boolean;
                        high_bidder_id?: string;
                        num_bids?: number;
                        price?: number;
                        type?: string;
                        make_an_offer?: boolean;
                        no_reserve?: boolean;
                        width?: number;
                        length?: number;
                        depth?: number;
                        weight?: number;
                        ends_at?: string;
                        created_at?: number;
                        has_video?: boolean;
                        seller?: string;
                        seller_country?: string;
                        on_sale?: boolean;
                        coupon_type?: string;
                        coupon_value?: string;
                        categories?: {
                            lvl0?: string;
                        };
                        variants?: Array<{
                            '2'?: string;
                        }>;
                        colours?: Array<(string)>;
                        image?: string;
                        url?: string;
                        url_store?: string;
                        description?: string;
                    };
                };
            };
        };
    };
    '/v3/guests/create': {
        post: {
            req: CreateAguestUserData;
        };
    };
};